In [2]:
import torch

In [3]:
test_tensor = torch.rand(10, 1, 28, 28)
test_tensor

tensor([[[[0.8048, 0.8669, 0.0215,  ..., 0.2968, 0.0362, 0.4277],
          [0.9732, 0.1212, 0.4760,  ..., 0.2377, 0.5882, 0.1594],
          [0.0860, 0.0470, 0.8315,  ..., 0.0973, 0.7062, 0.5110],
          ...,
          [0.0148, 0.9809, 0.0351,  ..., 0.4013, 0.6560, 0.5314],
          [0.6836, 0.3658, 0.8795,  ..., 0.7563, 0.7705, 0.9061],
          [0.2244, 0.8350, 0.5105,  ..., 0.9787, 0.5383, 0.1378]]],


        [[[0.7668, 0.6476, 0.1658,  ..., 0.4934, 0.8872, 0.9849],
          [0.7248, 0.1762, 0.9036,  ..., 0.5573, 0.1941, 0.3871],
          [0.7979, 0.9655, 0.4340,  ..., 0.0020, 0.0621, 0.1416],
          ...,
          [0.0407, 0.2729, 0.1160,  ..., 0.7991, 0.7778, 0.1089],
          [0.4861, 0.1757, 0.2714,  ..., 0.4965, 0.6291, 0.5179],
          [0.1454, 0.7007, 0.8673,  ..., 0.9644, 0.5076, 0.5877]]],


        [[[0.5852, 0.7252, 0.3410,  ..., 0.7886, 0.9542, 0.8657],
          [0.9950, 0.5990, 0.8920,  ..., 0.0424, 0.8511, 0.3977],
          [0.6997, 0.2414, 0.0870,  ..

In [6]:
test_tensor[:, 0, 0, 0]

tensor([0.8048, 0.7668, 0.5852, 0.3014, 0.7927, 0.5763, 0.9969, 0.5282, 0.5397,
        0.6958])

In [58]:
test_tensor[:, 1].view(2, -1)[:, 0] = 0
test_tensor[:, 1].view(2, -1)

tensor([[ 0,  8,  9, 10, 11, 12],
        [ 0, 20, 21, 22, 23, 24]])

In [42]:
test_tensor[:,0,:,:]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [ ]:
replace_tensor = torch.tensor([-10, -20])
test_tensor[:, 0, 0] = replace_tensor
print(test_tensor)

tensor([[[-10,   2,   3],
         [  4,   5,   6]],

        [[-20,   8,   9],
         [ 10,  11,  12]]])
